SELECT *
FROM SACH T1 LEFT JOIN CTHD T2 ON T1.MaSach = T2.MaSACH 
WHERE T2.MaSACH IS NULL

SELECT DISTINCT(T1.MaSach), T1.TenSach, T1.GiaTien, T1.SL, T1.Hinh, T1.UuTien, T1.MaTL, T1.MaNXB, T1.MaTG, T1.MaDM
FROM SACH T1 LEFT JOIN CTHD T2 ON T1.MaSach = T2.MaSACH 
WHERE T2.MaSACH IS NULL OR T2.MaSACH IN ( SELECT DISTINCT(T1.MaSach) FROM CTHD T1 JOIN HoaDon T2 On T1.MaHD = T2.MaHD WHERE DATEDIFF(MONTH, T2.Ngay ,GETDATE() ) > 6 )

ALTER PROC TonKHo
AS
	SELECT DISTINCT(T1.MaSach), T1.TenSach, T1.GiaTien, T1.SL, T1.Hinh, T1.UuTien, T1.MaTL, T1.MaNXB, T1.MaTG, T1.MaDM
	FROM SACH T1 LEFT JOIN CTHD T2 ON T1.MaSach = T2.MaSACH 
	WHERE T2.MaSACH IS NULL OR T2.MaSACH IN ( SELECT DISTINCT(T1.MaSach) FROM CTHD T1 JOIN HoaDon T2 On T1.MaHD = T2.MaHD WHERE DATEDIFF(MONTH, T2.Ngay ,GETDATE() ) > 6 )

EXEC TonKHo