SELECT ISNULL(SUM( (T2.SL*T3.GiaTien) - (T2.SL*T3.GiaTien*T2.KhuyenMai)),0)
FROM HoaDon T1 LEFT JOIN CTHD T2 ON T1.MaHD = T2.MaHD INNER JOIN Sach T3 ON T2.MaSACH = T3.MaSach
GROUP BY T1.MaHD


SELECT T1.MaHD, T2.MaSACH, T3.GiaTien
FROM HoaDon T1 LEFT JOIN CTHD T2 ON T1.MaHD = T2.MaHD INNER JOIN Sach T3 ON T2.MaSACH = T3.MaSach

SELECT ISNULL(SUM(T2.SL*T3.GiaTien),0)
FROM HoaDon T1 LEFT JOIN CTHD T2 ON T1.MaHD = T2.MaHD INNER JOIN Sach T3 ON T2.MaSACH = T3.MaSach
GROUP BY T1.MaHD