ALTER PROC PTop10
AS
SELECT TOP(10) T2.MaSach, T2.TenSach, Sum(T1.SL) As SoLuong, T2.GiaTien, T2.Hinh
FROM CTHD T1 JOIN Sach T2 On T1.MaSACH = T2.MaSach 
GROUP BY T2.MaSach, T2.TenSach, T2.GiaTien, T2.Hinh, T1.SL
ORDER BY SUM(T1.SL) DESC

SELECT T2.MaSach, T2.TenSach
FROM CTHD T1 JOIN Sach T2 On T1.MaSACH = T2.MaSach

SELECT SUM(SL)
FROM CTHD
GROUP BY MaSACH


SELECT T1.TenSach
FROM Sach T1 LEFT JOIN CTHD T2 ON T1.MaSach = T2.MaSACH

EXEC PTop10