CREATE TABLE KhachHang
(
	MaKH VARCHAR(10) PRIMARY KEY,
	TenKh VARCHAR(30),
	SoDT VARCHAR(11),
	Email VARCHAR(20)
);
CREATE TABLE NhanVien
(
	Manv VARCHAR(10) PRIMARY KEY,
	TenNV VARCHAR(30),
	SoDT VARCHAR(11),
	Email VARCHAR(20),
	ChucVu VARCHAR(20)
);

CREATE SEQUENCE PhieuNhap_seq;

CREATE TABLE PhieuNhap
(
	MaPN INT DEFAULT NEXTVAL ('PhieuNhap_seq') PRIMARY KEY,
	MaNCC VARCHAR(10),
	NgayNhap TIMESTAMP(3) DEFAULT NOW(),
	MaNV VARCHAR(10),
	TongTien Double precision
);

CREATE TABLE CTPhieu
(
	MaPN INT,
	MaSach VARCHAR(10),
	SL SMALLINT,
	ChietKhau DOUBLE PRECISION DEFAULT 0,
	DonGia Double precision,
	PRIMARY KEY(MaPN,MaSach)
);

CREATE TABLE NhaCungCap
(
	MaNCC VARCHAR(10) PRIMARY KEY,
	TenNCC VARCHAR(20),
	Diachi VARCHAR(200),
	SoDT VARCHAR(11)
);

CREATE TABLE TaiKhoan
(
	MaTK VARCHAR(10) PRIMARY KEY,
	TenTK VARCHAR(20),
	TenHienThi VARCHAR(50),
	MatKhau VARCHAR(20),
	ChucVu SMALLINT DEFAULT 0
);

CREATE TABLE TacGia
(	
	MaTG VARCHAR(10) PRIMARY KEY,
	TenTG VARCHAR(20),
	Email VARCHAR(20),
	SoDT VARCHAR(11)
);

CREATE TABLE NXB
(
	MaNXB VARCHAR(10) PRIMARY KEY,
	TenNXB VARCHAR(20),
	Email VARCHAR(20)
);

CREATE TABLE TheLoai
( 
	MaTL VARCHAR(10) PRIMARY KEY,
	TenTL VARCHAR(20),
	Mota VARCHAR(200)
);

CREATE TABLE Sach
(
	MaSach VARCHAR(10) PRIMARY KEY,
	TenSach VARCHAR(100),
	MaTL VARCHAR(10),
	MaNXB VARCHAR(10),
	MaTG VARCHAR(10),
	SL INT,
	GiaTien DOUBLE PRECISION,
	Hinh VARCHAR(50),
	UuTien INT NULL,
	MaDM INT
);

CREATE SEQUENCE HoaDon_seq;

CREATE TABLE HoaDon
(
	MaHD INT DEFAULT NEXTVAL ('HoaDon_seq') PRIMARY KEY,
	MaKH VARCHAR(10),
	Ngay DATE DEFAULT NOW(),
	TongTien DOUBLE PRECISION
);

CREATE TABLE CTHD
(
	MaHD INT,
	MaSACH VARCHAR(10),
	SL SMALLINT,
	KhuyenMai DOUBLE PRECISION DEFAULT 0,
	DonGia DOUBLE PRECISION,
	PRIMARY KEY(MaHD,MaSach)
);

CREATE SEQUENCE DanhMuc_seq;

CREATE TABLE DanhMuc
(
	MaDM INT DEFAULT NEXTVAL ('DanhMuc_seq') NOT NULL PRIMARY KEY,
	TenDM VARCHAR(50),
	MetaTitle VARCHAR(100) NULL
);
Create sequence SaveHistory_seq;

Create Table SaveHistory
(
	ID Int Default nextval ('SaveHistory_seq') Primary Key,
	AuditCode Varchar(50),
	AuditDate Timestamp(3),
	AuditItemID Varchar(100),
	Description Varchar (4000),
	EventID Varchar (50),
	IP Varchar(250),
	UserID Varchar(100)
);

ALTER TABLE PhieuNhap
ADD CONSTRAINT FK_PN_NV FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV)
ALTER TABLE PhieuNhap
ADD CONSTRAINT FK_PN_NCC FOREIGN KEY(MaNCC) REFERENCES NhaCungCap(MaNCC)

ALTER TABLE CTPhieu
ADD CONSTRAINT FK_CTP_PN FOREIGN KEY(MaPN) REFERENCES PhieuNhap(MaPN)
ALTER TABLE CTPhieu
ADD CONSTRAINT FK_CTP_Sach FOREIGN KEY(MaSach) REFERENCES Sach(MaSach)

ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_TL FOREIGN KEY(MaTL) REFERENCES TheLoai(MaTL)
ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_TG FOREIGN KEY(MaTG) REFERENCES TacGia(MaTG)
ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_NXB FOREIGN KEY(MaNXB) REFERENCES NXB(MaNXB)
ALTER TABLE Sach
ADD CONSTRAINT FK_Sach_DanhMuc FOREIGN KEY(MaDM) REFERENCES DanhMuc(MaDM)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_Sach FOREIGN KEY(MaSach) REFERENCES Sach(MaSach)
ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)

ALTER TABLE HoaDon
ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH);
 
